init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: "4.2.2"

install:
  - npm install

test_script:
  - cmd: npm install artillery

version: "{build}"
build: off
